[package]
name = "zookeeper"
version = "0.1.0"
authors = ["Justin Wei <wei.justin.a@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timer = "0.2.0"
chrono = "0.4"
serde_json = "1.0"
rand = "0.7.3"
